# Generated by Django 4.2.13 on 2024-05-12 13:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicqualification',
            name='start_year',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 5, 12))]),
        ),
    ]
