# Generated by Django 4.2.13 on 2024-05-16 07:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_useraccount_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='start_year',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 5, 16))]),
        ),
    ]
