# Generated by Django 4.2.13 on 2024-05-11 12:23

import adverts.models
import ckeditor.fields
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('advert_type', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], default='External', max_length=20)),
                ('status', models.CharField(choices=[('published', 'Published'), ('closed', 'Closed'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('closing_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 5, 11))])),
                ('number_of_posts', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Advert',
                'verbose_name_plural': 'Adverts',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('comments', models.TextField(blank=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('offered_job', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to=settings.AUTH_USER_MODEL)),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_post', to='adverts.advert')),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_date', models.DateTimeField(auto_now_add=True)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.advert')),
                ('interview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_offer', to='adverts.interview')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JobOfferReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=1000, null=True)),
                ('attachment', models.FileField(upload_to='')),
                ('reply_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_offer_reply', to='adverts.joboffer')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True)),
                ('venue', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_invitation', to='adverts.advert')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_invited', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='applications/cover_letters/', validators=[django.core.validators.FileExtensionValidator(['doc', 'pdf']), adverts.models.validate_file_mimetype, adverts.models.validate_file_size])),
                ('resume', models.FileField(blank=True, null=True, upload_to='applications/resume', validators=[django.core.validators.FileExtensionValidator(['doc', 'pdf']), adverts.models.validate_file_mimetype, adverts.models.validate_file_size])),
                ('status', models.CharField(choices=[('shortlist', 'Shortlist'), ('reject', 'Reject'), ('interview', 'Interview'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('comment', models.TextField()),
                ('date_applied', models.DateTimeField(default=django.utils.timezone.now)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='adverts.advert')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requirements_met', models.ManyToManyField(related_name='requirements_met', to='adverts.requirement')),
            ],
        ),
        migrations.AddField(
            model_name='advert',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.department'),
        ),
        migrations.AddField(
            model_name='advert',
            name='requirements',
            field=models.ManyToManyField(related_name='requirements', to='adverts.requirement'),
        ),
    ]
