# Generated by Django 4.2.13 on 2024-05-12 13:23

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='cover_letter',
            new_name='documents',
        ),
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
        migrations.AlterField(
            model_name='advert',
            name='closing_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 5, 12))]),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Dr', 'Dr')], max_length=5)),
                ('full_name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('organization', models.CharField(max_length=1000)),
                ('position', models.CharField(max_length=1000)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='adverts.application')),
            ],
        ),
    ]
