# Generated by Django 4.2.13 on 2024-05-14 17:03

import adverts.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_rename_cover_letter_application_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='interview',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_offer', to='adverts.application'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='applications/job_offer/', validators=[django.core.validators.FileExtensionValidator(['doc', 'pdf']), adverts.models.validate_file_mimetype, adverts.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='advert',
            name='closing_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 5, 14))]),
        ),
    ]
