# Generated by Django 4.2.13 on 2024-05-15 09:20

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_remove_joboffer_interview_joboffer_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='closing_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 5, 15))]),
        ),
        migrations.CreateModel(
            name='EmailReferee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='adverts.application')),
                ('referee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referee', to='adverts.reference')),
            ],
        ),
    ]
