# Generated by Django 4.2.13 on 2024-05-15 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_alter_advert_closing_date_emailreferee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailreferee',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adverts.application'),
        ),
        migrations.AlterField(
            model_name='emailreferee',
            name='referee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adverts.reference'),
        ),
    ]
