# Generated by Django 4.2.13 on 2024-05-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0007_rename_application_emailreferee_app_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailreferee',
            old_name='app',
            new_name='application',
        ),
        migrations.RenameField(
            model_name='emailreferee',
            old_name='ref',
            new_name='referee',
        ),
    ]
