# Generated by Django 4.2.13 on 2024-05-16 07:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0010_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='closing_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 5, 16))]),
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
