from django.urls import path
from .views import (
    new_requirement, new_department, AdvertListView, NewAdvert,
    advert_detail, NewApplication, edit_advert, advert_delete, requirement_delete,
    edit_requirement, edit_department, department_delete,
    advert_requirements, add_advert_requirements, delete_advert_requirement,
    advert_preview, publish_advert, applications, application_detail, requirements_met,
    interview_invite, interview, interview_mark,
    interview_scores, application_feedback, application_interview_score,
    search_adverts, applied_jobs, job_offer_reply, view_reply,
    AddAcademicQualification, add_experience, experience_and_qualifications, send_job_offer, send_email_to_referee,
    summary_table, export_summary_table, EditQualification, EditExperience, update_application_status, ApplyingWizardView,
    pdf_summary_table, generateSummaryTablePDF, filter_adverts
)

app_name = "adverts"
urlpatterns = [
    path('filter-adverts', filter_adverts, name="filter_adverts"),
    path("", AdvertListView.as_view(), name="adverts"),
    path("adverts/<int:pk>/pdf-summary-table",
         pdf_summary_table, name="pdf_summary_table"),
    path("adverts/<int:pk>/generate-pdf-summary-table",
         generateSummaryTablePDF, name="generate_summary_table"),
    path('<int:id>/applications/<int:pk>/job-offer',
         send_job_offer, name="send_job_offer"),
    path("<int:id>/applications/<int:pk>/email-referee/<int:referee_id>",
         send_email_to_referee, name="send_email_to_referee"),
    path("<int:id>/advert-application/", ApplyingWizardView.as_view(),
         name="advert-application"),
    path('adverts-search/', search_adverts, name="search_adverts"),
    path("applied", applied_jobs, name="applied_jobs"),
    path("qualifications/<int:pk>/edit/",
         EditQualification.as_view(), name="edit_qualification"),
    path("experience/<int:pk>/edit/",
         EditExperience.as_view(), name="edit_experience"),
    path("adverts/<int:id>/", advert_detail, name="advert_detail"),
    path("adverts/<int:id>/applications/<int:pk>/requirements_met",
         requirements_met, name="requirements_met"),
    path('adverts/<int:id>/applications/<int:pk>/interview_invitations', interview_invite,
         name="interview_invite"),
    path('adverts/<int:id>/applications/<int:pk>/interview', interview,
         name="interview"),
    path('adverts/<int:id>/summary_table', summary_table,
         name="summary_table"),
    path('adverts/<int:id>/export_summary_table', export_summary_table,
         name="export_summary_table"),
    path('adverts/<int:id>/interviews/<int:pk>/reply', view_reply,
         name="view_reply"),
    path('adverts/<int:id>/interview_scores', interview_scores,
         name="interview_scores"),
    path('adverts/<int:id>/applications/<int:pk>/interview-mark', application_interview_score,
         name="application_interview_score"),
    path('adverts/<int:id>/applications/<int:pk>/status', update_application_status,
         name="update_application_status"),
    path('adverts/<int:id>/application_feedback', application_feedback,
         name="application_feedback"),

    path('adverts/<int:id>/job_offers/<int:pk>/job_offer_reply', job_offer_reply,
         name="job_offer_reply"),
    path('adverts/<int:id>/applications/<int:pk>/interview-mark', interview_mark,
         name="interview_mark"),
    path("adverts/<int:id>/applications", applications, name="applications"),
    path("adverts/<int:id>/applications/<int:pk>/",
         application_detail, name="application_detail"),
    path("adverts/<int:id>/preview", advert_preview, name="advert_preview"),
    path("adverts/<int:id>/publish", publish_advert, name="publish_advert"),
    path("adverts/<int:id>/requirements",
         advert_requirements, name="advert_requirements"),
    path("adverts/<int:id>/requirements/<int:pk>/delete",
         delete_advert_requirement, name="delete_advert_requirement"),
    path("adverts/<int:id>/requirements/add",
         add_advert_requirements, name="add_advert_requirements"),
    path("adverts/<int:id>/delete",
         advert_delete, name="advert_delete"),
    path("departments/<int:id>/delete",
         department_delete, name="department_delete"),
    path("adverts/<int:id>/requirements/<int:pk>/delete",
         requirement_delete, name="requirement_delete"),
    path("adverts/<int:id>/edit", edit_advert, name="edit_advert"),
    path("adverts/<int:id>/requirements/<int:pk>/edit",
         edit_requirement, name="edit_requirement"),
    path("departments/<int:id>/edit", edit_department, name="edit_department"),
    path("adverts/<int:id>/apply/", NewApplication.as_view(), name="apply"),
    path("add_academic_qualification/", AddAcademicQualification.as_view(),
         name="add_academic_qualification"),
    path("experience_and_qualifications/", experience_and_qualifications,
         name="experience_and_qualifications"),
    path("add_experience/", add_experience, name="add_experience"),
    path("new_advert/", NewAdvert.as_view(), name="new_advert"),
    path("new_requirement/", new_requirement, name="new_requirement"),
    path("new_department/", new_department, name="new_department"),
]
